// <auto-generated />
using System;
using JobsCalc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobsCalc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250227225016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobsCalc.Domain.Entities.JobEntity", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DailyHours")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("JobsCalc.Domain.Entities.PlanningEntity", b =>
                {
                    b.Property<Guid>("PlanningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("HoursPerDay")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyBudget")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VacationPerYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueHour")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("PlanningId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("plannings", (string)null);
                });

            modelBuilder.Entity("JobsCalc.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JobsCalc.Domain.Entities.JobEntity", b =>
                {
                    b.HasOne("JobsCalc.Domain.Entities.UserEntity", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobsCalc.Domain.Entities.PlanningEntity", b =>
                {
                    b.HasOne("JobsCalc.Domain.Entities.UserEntity", "User")
                        .WithOne("Planning")
                        .HasForeignKey("JobsCalc.Domain.Entities.PlanningEntity", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobsCalc.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Planning");
                });
#pragma warning restore 612, 618
        }
    }
}
